(ns hipstr.routes.home
  (:require [hipstr.layout :as layout]
            [compojure.core :refer [defroutes GET]]
            [clojure.java.io :as io]))

(defn home-page []
  (layout/render
    "home.html" {:docs (-> "docs/docs.md" io/resource slurp)}))

(defn about-page []
  (layout/render "about.html"))

(defn foo-response [request]
  {:status 200
   :headers {"Content-Type" "text/html"}
   :body (str "<html><body><dt>Bowling much?</dt>"
              "<dd>" (:go-bowling? request) "</dd></body></html>")})
  

(defroutes home-routes
  ;; this route servers hipstr's root page, generated by fn
  ;; 'home-page'
  (GET "/" [] (home-page)) 
  (GET "/about" [] (about-page))
  ;; (GET "/about" request (foo-response request)))
  ;; (ANY "/req" request (str request)) ; ANY is macro from where?
  ;; (GET "/req" request (str request))
  
  )
  
